settings:
  general:
    firstload: true
    enable: true
    locale: en_US
  flashlight:
    enable: true
    usepermission: true
    candrop: false
    dropondeath: false
  craftable:
    ==: SerializedSettings
    enable: true
    id: 1
    goldsight:
      ==: SerializedCraftSettings
      usepermission: true
      candrop: true
      maxLight: 20
      dropondeath: true
      name: GoldSight
      enable: true
      craftpermission: true
    ironsight:
      ==: SerializedCraftSettings
      usepermission: true
      candrop: true
      maxLight: 10
      dropondeath: true
      name: IronSight
      enable: true
      craftpermission: true
    diamondsight:
      ==: SerializedCraftSettings
      usepermission: true
      candrop: true
      maxLight: 45
      dropondeath: true
      name: DiamondSight
      enable: true
      craftpermission: true
    emeraldsight:
      ==: SerializedCraftSettings
      usepermission: true
      candrop: true
      maxLight: 60
      dropondeath: true
      name: EmeraldSight
      enable: true
      craftpermission: true
flashlight: []
recipies:
  recipe: []

