name: HoldableTorches
main: org.codemine.holdabletorches.Torches
author: Minecraftfailzzz
authors: [StashCat,webbhead,Relicum]
version: ${project.version}
description: Hold a torch and you will get NightVision

commands:
  ironsight:
    description: Display Crafting recipe for Iron Site Torch
    usage: /ironsight
    permission: torchiron.use
  goldsight:
    description: Display Crafting recipe for Gold Site Torch
    usage: /goldsight
    permission: torchgold.use
  diamondsight:
    description: Display Crafting recipe for Diamond Site Torch
    usage: /diamondsight
    permission: torchdiamond.use
  emeraldsight:
    description: Display Crafting recipe for Emerald Site Torch
    usage: /emeraldsight
    permission: torchemerald.use

permissions:
    torchiron.use:
        description: Allows the player to craft the Iron Sight Torch
        default: op
    torchgold.use:
        description: Allows the player to craft the Gold Sight Torch
        default: op
    torchdiamond.use:
        description: Allows the player to craft the Diamond Sight Torch
        default: op
    torchemerald.use:
        description: Allows the player to craft the Emerald Sight Torch
        default: op