name: Holdable Torches
main: org.codemine.holdabletorches.Torches
author: Minecraftfailzzz
authors: [StashCat,webbhead,Relicum]
version: ${project.version}
description: Hold a torch and you will get NightVision

commands:
  flashlight:
    description: Get a new HoldAble Torch
    usage: /flashlight
    permission: holdabletorches.use
  ironsight:
    description: Display Crafting recipe for Iron Site Torch
    usage: /ironsight
    permission: holdabletorches.use

permissions:
    holdabletorches.use:
        description: allows a player to use the torches to get the effect.
        default: op